"""Interview Plan Pydantic models (REQ-02).

Defines the structured data model for generated interview plans
and web research results consumed by the Planner subgraph.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


class SearchResult(BaseModel):
    """A single search result from Tavily or other sources."""

    title: str
    content: str
    url: str


class FocusArea(BaseModel):
    """A focus area for the interview with relative weight."""

    area: str = Field(description="Focus area name, e.g. 'System Design'")
    weight: float = Field(ge=0.0, le=1.0, description="Relative importance (0.0-1.0)")
    reason: str = Field(description="Why this area is important for this role")


class WebResearch(BaseModel):
    """Aggregated web research results for interview preparation."""

    interview_experience: list[SearchResult] = Field(default_factory=list)
    company_tech_stack: list[SearchResult] = Field(default_factory=list)
    common_questions: list[SearchResult] = Field(default_factory=list)


class InterviewPlan(BaseModel):
    """Structured interview plan generated by the Planner agent."""

    target_company: str
    target_position: str
    job_requirements: str | None = Field(default=None, description="Job requirements summary from JD")
    tech_stack: list[str] = Field(default_factory=list)
    interview_difficulty: str = Field(default="medium", pattern=r"^(easy|medium|hard)$")
    focus_areas: list[FocusArea] = Field(default_factory=list)
    suggested_questions: list[str] = Field(default_factory=list)
    web_research_summary: str | None = Field(default=None, description="Summary of web research findings")
    tips: list[str] = Field(default_factory=list)


__all__ = [
    "FocusArea",
    "InterviewPlan",
    "SearchResult",
    "WebResearch",
]
