import os, re

DICT = {
  '## 关键概念': '## Key concepts',
  '## 工作机制': '## Mechanism',
  '## 故障模式': '## Failure modes',
  '## 准入条件': '## Admission conditions',
  '## 输入格式': '## Input format',
  '## 输出格式': '## Output format',
  '## 检测算法': '## Detection algorithm',
  '## 典型场景': '## Typical scenarios',
  '## 适用条件': '## When to apply',
  '## 评估指标': '## Evaluation metrics',
  '## 最佳实践': '## Best practices',
  '## 注意事项': '## Caveats',
  '## 风险与权衡': '## Risks and trade-offs',
  '## 集成点': '## Integration points',
  '## 调用时机': '## When called',
  '## 调用契约': '## Call contract',
  '## 与 v1.x 的差异': '## Changes from v1.x',
  '## 跨团队契约': '## Cross-team contracts',
  '## 性能开销': '## Performance overhead',
  '## 失败处理': '## Failure handling',
  '## 重试策略': '## Retry strategy',
  '## 错误恢复': '## Error recovery',
  '## 集成示例': '## Integration example',
  '## 配置项': '## Configuration',
  '## 默认值': '## Defaults',
  '## 已知问题': '## Known issues',
  '## 参考实现': '## Reference implementation',
  '## 决策表': '## Decision table',
  '## 优化建议': '## Optimization tips',
  '## 模板': '## Template',
  '## 协议': '## Protocol',
  '## 历史': '## History',
  '## 总结': '## Summary',
  '## 原则': '## Principles',
  '## 反例': '## Counter-examples',
  '## 示例': '## Examples',
  '## 例子': '## Examples',
  '## 输入': '## Input',
  '## 输出': '## Output',
  '## 用法': '## Usage',
  '## 说明': '## Notes',
  '## 备注': '## Notes',
  '## 背景': '## Background',
  '## 范围': '## Scope',
  '## 目标': '## Goals',
  '## 约束': '## Constraints',
  '## 假设': '## Assumptions',
  '## 限制': '## Limitations',
  '## 替代方案': '## Alternatives',
  '## 推荐': '## Recommendation',
  '## 步骤': '## Steps',
  '## 流程': '## Flow',
  '## 指标': '## Metrics',
  '## 监控': '## Monitoring',
  '## 告警': '## Alerts',
  '## 告警规则': '## Alert rules',
  '## 资源': '## Resources',
  '## 工具': '## Tools',
  '## 命令': '## Commands',
  '## 脚本': '## Scripts',
  '## 案例': '## Cases',
  '## 常见错误': '## Common mistakes',
  '## 性能': '## Performance',
  '## 安全': '## Security',
  '## 兼容性': '## Compatibility',
  '## 可扩展性': '## Extensibility',
  '## 测试用例': '## Test cases',
  '## API': '## API',
  '## 架构': '## Architecture',
  '## 流程图': '## Flow diagram',
  '## 状态机': '## State machine',
  '## 状态图': '## State diagram',
  '## 数据流': '## Data flow',
  '## 时序': '## Sequence',
  '## 时序图': '## Sequence diagram',
  '## 接口': '## Interface',
  '## 契约': '## Contract',
  '## 协议细节': '## Protocol details',
  '## 字段说明': '## Field reference',
  '## 字段表': '## Field table',
  '## 错误码': '## Error codes',
  '## 状态码': '## Status codes',
  '## 响应': '## Response',
  '## 请求': '## Request',
  '## 路径': '## Path',
  '## 方法': '## Method',
  '## 标头': '## Headers',
  '## 参数': '## Parameters',
  '## 返回值': '## Return value',
  '## 数据结构': '## Data structure',
  '## 存储': '## Storage',
  '## 索引': '## Index',
  '## 查询': '## Query',
  '## 数据库': '## Database',
  '## 表结构': '## Table schema',
  '## 迁移': '## Migration',
  '## 种子': '## Seed',
  '## 部署': '## Deployment',
  '## 运维': '## Operations',
  '## 排错': '## Troubleshooting',
  '## FAQ': '## FAQ',
  '## 总结回顾': '## Recap',
  '## 关键点': '## Key points',
  '## 重要提示': '## Important',
  '## 实践': '## Practice',
  '## 模式': '## Patterns',
  '## 反模式': '## Anti-patterns',
  '## 经验': '## Lessons',
  '## 教训': '## Lessons',
  '## 启发': '## Takeaways',
  '## 反馈': '## Feedback',
  '## 改进': '## Improvements',
  '## 演进': '## Evolution',
  '## 版本': '## Version',
  '## 更新': '## Changelog',
  '## 变更': '## Changes',
  '## 路线图': '## Roadmap',
  '## 后续': '## Follow-up',
  '## 计划': '## Plan',
  '## 行动': '## Actions',
  '## 决策': '## Decisions',
  '## 待办': '## TODO',
  '## 记录': '## Records',
  '## 归档': '## Archive',
  '## 评估': '## Evaluation',
  '## 评审': '## Review',
  '## 验收': '## Acceptance',
  '## 准入': '## Gate',
  '## 门控': '## Gate',
  '## 退出条件': '## Exit conditions',
  '## 完成定义': '## Definition of done',
  '## 回滚': '## Rollback',
  '## 清理': '## Cleanup',
  '## 复位': '## Reset',
  '## 重启': '## Restart',
  '## 停机': '## Shutdown',
  '## 启动': '## Startup',
  '## 健康检查': '## Health check',
  '## 超时': '## Timeout',
  '## 重试': '## Retry',
  '## 限流': '## Rate limit',
  '## 熔断': '## Circuit breaker',
  '## 降级': '## Degradation',
  '## 隔离': '## Isolation',
  '## 沙箱': '## Sandbox',
  '## 模拟': '## Mock',
  '## 桩': '## Stub',
  '## 替身': '## Test double',
  '## 假数据': '## Fake data',
  '## 测试数据': '## Test data',
  '## 准备': '## Setup',
  '## 拆卸': '## Teardown',
  '## 钩子': '## Hook',
  '## 前置': '## Before',
  '## 后置': '## After',
  '## 包裹': '## Wrap',
  '## 装饰': '## Decorator',
  '## 拦截': '## Interceptor',
  '## 切面': '## Aspect',
  '## 切点': '## Pointcut',
  '## 连接点': '## Join point',
  '## 通知': '## Advice',
  '## 引入': '## Introduction',
  '## 目标对象': '## Target',
  '## 代理': '## Proxy',
  '## 工厂': '## Factory',
  '## 单例': '## Singleton',
  '## 多例': '## Multi-instance',
  '## 原型': '## Prototype',
  '## 建造者': '## Builder',
  '## 抽象工厂': '## Abstract factory',
  '## 策略': '## Strategy',
  '## 模板方法': '## Template method',
  '## 观察者': '## Observer',
  '## 发布订阅': '## Pub-sub',
  '## 状态': '## State',
  '## 命令模式': '## Command',
  '## 责任链': '## Chain of responsibility',
  '## 中介者': '## Mediator',
  '## 备忘录': '## Memento',
  '## 解释器': '## Interpreter',
  '## 访问者': '## Visitor',
  '## 迭代器': '## Iterator',
  '## 生成器': '## Generator',
  '## 适配器': '## Adapter',
  '## 桥接': '## Bridge',
  '## 组合': '## Composite',
  '## 装饰器': '## Decorator',
  '## 外观': '## Facade',
  '## 享元': '## Flyweight',
  '## 私有': '## Private',
  '## 保护': '## Protected',
  '## 公开': '## Public',
  '## 静态': '## Static',
  '## 实例': '## Instance',
  '## 类': '## Class',
  '## 对象': '## Object',
  '## 接口定义': '## Interface definition',
  '## 实现细节': '## Implementation',
  '## 业务规则': '## Business rules',
  '## 业务逻辑': '## Business logic',
  '## 数据模型': '## Data model',
  '## 领域模型': '## Domain model',
  '## 实体': '## Entity',
  '## 值对象': '## Value object',
  '## 聚合': '## Aggregate',
  '## 仓储': '## Repository',
  '## 服务': '## Service',
  '## 控制器': '## Controller',
  '## 视图': '## View',
  '## 模型': '## Model',
  '## 路由': '## Route',
  '## 控制器方法': '## Controller method',
  '## 中间件': '## Middleware',
  '## 过滤器': '## Filter',
  '## 异常处理': '## Exception handling',
  '## 错误页': '## Error page',
  '## 日志': '## Logging',
  '## 审计': '## Audit',
  '## 追踪': '## Tracing',
  '## 指标采集': '## Metrics collection',
  '## 度量': '## Metrics',
  '## 健康': '## Health',
  '## 状态检查': '## Status check',
  '## 依赖': '## Dependencies',
  '## 第三方': '## Third-party',
  '## 内部': '## Internal',
  '## 外部': '## External',
}

BILI_RE = re.compile(r'^(#{1,4})\s+([^/\n]+?)\s*/\s*([^\n]+?)\s*$', re.MULTILINE)

def strip_bili(m):
    prefix, a, b = m.group(1), m.group(2).strip(), m.group(3).strip()
    if re.search(r'[a-zA-Z]', a):
        return f'{prefix} {a}'
    return f'{prefix} {b}'

files = [
  'self-healing.md','deterministic-gates.md','independent-reverification.md',
  'scope-based-testing.md','flaky-analysis.md','visual-regression.md',
  'ci-cd-integration.md','redteam-strategy.md','browser-strategy.md',
  'mcp-detection.md','project-type-detection.md','db-type-mapping.md',
  'failure-attribution.md',
]

os.chdir('D:/Project/eGGG/.claude/skills/test-acceptance/references')
total = 0
for fn in files:
    with open(fn, 'r', encoding='utf-8') as f:
        s = f.read()
    orig = s
    s = BILI_RE.sub(strip_bili, s)
    for zh, en in DICT.items():
        s = re.sub(rf'^{re.escape(zh)}\s*$', en, s, flags=re.MULTILINE)
    if s != orig:
        with open(fn, 'w', encoding='utf-8') as f:
            f.write(s)
        total += 1
        print(f'updated: {fn}')

print(f'TOTAL: {total}/13')
